# **Ejercicios de NumPy**

In [31]:
%pylab inline
import numpy as np

#Para las preguntas 5 y 6
import math 
import matplotlib.pyplot as plt

Populating the interactive namespace from numpy and matplotlib


**Pregunta 1**

Crea los siguientes arreglos con los tipos correctos.

1. Un arreglo de $5 \times 5$ cuya diagonal sean $[0.1, 2.0, 3.0, 4.0, 5.0]$

2. Un arreglo de $4 \times 4$ cuyo último renglón sea $[1,2,3,4]$ y el resto sean $0$.

In [4]:
arr1 = np.eye(5)
for i in range(0,5): 
    arr[i][i] += i 
arr

array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]])

In [6]:
arr2 = np.zeros((4,4))
arr2[3] = np.arange(4) + 1
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 2., 3., 4.]])

**Pregunta 2**

En este ejercicio realizaremos una criba de Eratóstenes.

(a) Crea un arreglo de booleanos de shape (100), con todos sus elementos True. El índice representa el número.

(b) "Tacha" los elementos 0 y 1.

(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el slicing.

(d) Mira la documentacion de np.nonzero para imprimir todos los números primos.

(e) Encapsula lo que acabamos de hacer en una función llamada criba_eratostenes, que reciba como argumento maximo el cual representa el tamaño del array. Muestra el resultado para maximo = {10, 100, 200}, usando un for.

In [11]:
#(a) Crea un arreglo de booleanos de shape (100), con todos sus elementos True. El índice representa el número.
bool_arr = np.ones((100), dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [13]:
#(b) "Tacha" los elementos 0 y 1.
bool_arr[0] = False
bool_arr[1] = False
bool_arr

array([False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [14]:
#(c) Para cada entero subsiguiente, tacha sus múltiplos. Una manera de hacerlo es el código que se muestra. Explica que hace el código, sobretodo explica que hace el slicing.

N_max = int(np.sqrt(len(bool_arr))) #len me dice cuántos elementos hay en el arreglo, tomamos la raíz de ese número y lo convertimos en un entero. Ese es el máximo al que llegará nuestro for. 
for j in range(2, N_max):
    bool_arr[2*j::j] = False #marca los valores 2j, 3j, 4j, 5j... como falsos, hasta que no tiene más valores
bool_arr

array([False, False,  True,  True, False,  True, False,  True, False,
       False, False,  True, False,  True, False, False, False,  True,
       False,  True, False, False, False,  True, False, False, False,
       False, False,  True, False,  True, False, False, False, False,
       False,  True, False, False, False,  True, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False,  True, False,  True, False,
       False, False, False, False,  True, False, False, False,  True,
       False,  True, False, False, False, False, False,  True, False,
       False, False,  True, False, False, False, False, False,  True,
       False, False, False, False, False, False, False,  True, False,
       False])

In [17]:
#(d) Mira la documentacion de np.nonzero para imprimir todos los números primos. --> CHECK
np.nonzero(bool_arr)

(array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
        61, 67, 71, 73, 79, 83, 89, 97]),)

In [18]:
#(e) Encapsula lo que acabamos de hacer en una función llamada criba_eratostenes, que reciba como argumento maximo el cual representa el tamaño del array. Muestra el resultado para maximo = {10, 100, 200}, usando un for.
#FALTAAA
#FALTAAA
#FALTAAA
#FALTAAA
#FALTAAA

**Pregunta 3**

Crea un cubo rubik, partiendo de un arreglo de ceros y usando slicing dibuja cada una de las caras como si estuviera resuelto (cada color un entero a partir del $1$). Muestra con indexing que está resuelto (es decir, imprime las seis caras). ¿Cuántos elementos del arreglo quedaron en $0$?

In [21]:
#Cualquier cubo tiene 6 lados, viendo cada cara como una matriz tienen que ser 3x3 (si es un cubo rubik tradicional)
crubik = np.zeros((6,3,3))
#indexing
for i in range(6):
    crubik[i] = i + 1
crubik

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]],

       [[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]],

       [[6., 6., 6.],
        [6., 6., 6.],
        [6., 6., 6.]]])

Ningún elemento del arreglo quedó en cero. 

**Pregunta 4**

El Sudoku es un pasatiempo que consiste en un arreglo $9 \times 9$ de celdas, con dígitos del 1 al 9, de tal manera que no se repiten valores en cada columna, cada renglón y en cada subarreglo de $3\times 3$.

(a) Crea una función llamada correcto que reciba un array $1d$ de tamaño 9 e indique si está completo o no (i.e. incluye los números del 1 al 9.

(b) Crea una función llamada descomponer3x3 que reciba un array de enteros de $9\times 9$ y lo separe en sus 9 subarreglos $3\times3$.

(c) Crea la función esSolucion que recibe un array de $9\times 9$ y devuelve si es o no solución del sudoku.

In [75]:
#Defino mi primera función
def correcto(arr):
    if len(arr) == 9:
        for i in range (1,10): #again, porque el cero es natural
            if i not in arr: 
                return "No es un número del 1 al 9"
        else: 
            return "Es correcto"
    else: 
        return "No son 9 números"

In [79]:
#Hago pruebas de que funciona
arr = np.arange(1,10) #no suelta error, wuu
print (correcto(arr))
arr0 = np.arange(0,4) #tampoco suelta error wuuu
print (correcto(arr0))

Es correcto
No son 9 números
No son 9 números


In [80]:
#Defino mi segunda función
def descomponer3x3(arr):
    separar = np.reshape(arr,(9,3,3))
    return separar

In [81]:
ejemplo = np.identity(9)
print (descomponer3x3(ejemplo))

[[[1. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 1. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 1.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [1. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 1. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 1.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [1. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 1. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 1.]]]


Again, me está ganando el tiempo PERO intentaré el inciso c el fin de semana. 

**Pregunta 5**

Utiliza el archivo sunspots.txt (localizado en la carpeta data), el cual contiene el número de manchas solares por cada mes desde enero de 1749. La primera columna es el mes, el segundo el número de manchas.

(a) Escribe el código que lea el archivo y haga una gráfica de las manchas en función del tiempo. Formatea el eje 𝑥 para que se muestren cada 25 años empezando en 1750.

(b) Calcula el promedio móvil. Dibújalo sobre el dibujo original.

In [60]:
archivo = open('sunspots.txt')
datos1 = archivo.read()
archivo.close()
print (datos1) #lo usé para verificar

datos2 = datos2.split('\n') #separo mes y manchas
datos2 = [i.split(' ') for i in datos2] 
mes = []
manchas = []

for i in range(len(datos1)-1): #porque el cero es natural :P
    mes = mes.append((float((datos2[i][0]))
    manchas = manchas.append(float(datos2[i][1]))

SyntaxError: invalid syntax (<ipython-input-60-0d6dcca26638>, line 13)

**Pregunta 6**

Utiliza el archivo stars.txt (localizado en la carpeta data), el cual contiene la temperatura y magnitud de varias estrellas en la Vía Lactea. Usa esta información para dibujar un scatter plot del logaritmo del brillo vs. la temperatura (en K). Este diagrama se conoce como diagrama de Hertzsprung-Russell.

In [58]:
archivo = open('stars.txt')
datos2 = archivo.read()
archivo.close()
#print (datos2) lo usé para verificar

datos2 = datos2.split('\n') #separo brillo y temperatura
datos2 = [i.split(' ') for i in datos2] 
brillo = []
tempe = []

for i in range(len(datos2)-1): #porque el cero es natural :P
    brillo = brillo.append((float((datos2[i][0]))
    tempe = tempe.append(float(datos2[i][1]))
    
plt.figure(figsize=(12, 8), dpi=80)
    
plt.scatter(brillo,temp,color=color['color'], linewidth=.5, linestyle="-")

SyntaxError: invalid syntax (<ipython-input-58-738d8a53ad15>, line 13)

**Pequeña nota para el profesor**

Prof, tengo el mismo error en la 4 y en la 5 pero ya es muy tarde y la verdad no he encontrado solución al problema y creo que hasta estoy googoleando mal. Aunque no cuente para la entrega de la tarea le voy a dar una segunda vez el fin de semana y espero que salga, no me voy a rendir jajajaja. ¡Muchas gracias y lindo fin!